config/routes.rb
Rails.application.routes.draw do
  devise_for :users 
  root to: 'pages#home'
  
  resources :patients, only:  %i[new create show index]  
  resources :doctors, only:  %i[new create]  
  resources :before_exercises, only:  %i[new create]  
  resources :after_exercises, only:  %i[new create]  

end

app/models/after_exercise.rb
class AfterExercise < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/before_exercise.rb
class BeforeExercise < ApplicationRecord
  belongs_to :user
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  has_many :patients
  has_many :posts
end

app/models/doctor_post.rb
class DoctorPost < ApplicationRecord
  belongs_to :user
end

app/models/patient.rb
class Patient < ApplicationRecord
  belongs_to :doctor
  has_many :posts
  has_many :before_exercises
  has_many :after_exercises
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
        
  has_many :doctor_posts
  has_many :before_exercises
  has_many :after_exercises
end

app/controllers/after_exercises_controller.rb
class AfterExercisesController < ApplicationController

  def new
    @after_exercise = AfterExercise.new
  end

  def create
    @after_exercise = AfterExercise.new(after_exercise_params)
    @after_exercise.user = current_user
    @after_exercise.sent = false # consultar bien si esta ligada a user o users_info
    if @after_exercise.save
      redirect_to new_after_exercise(@after_exercise)
    else
      render :new
    end
  end


  private

  def after_exercise_params
    params.require(:after_exercise).permit(:input_before, :anxiety_level, :motivation_level, :mood_level, :cardiac_frequency, :respiratory_rate , :pain)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/before_exercises_controller.rb
class BeforeExercisesController < ApplicationController

  def new
    @before_exercise = BeforeExercise.new
  end

  def create
    @before_exercise = BeforeExercise.new(before_exercise_params)
    @before_exercise.user = current_user
    @before_exercise.sent = false # consultar bien si esta ligada a user o users_info
    if @before_exercise.save
      redirect_to new_before_exercise(@before_exercise)
    else
      render :new
    end
  end

  private

  def before_exercise_params
    params.require(:before_exercise).permit(:input_before, :anxiety_level, :motivation_level, :mood_level, :cardiac_frequency, :respiratory_rate , :pain)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  def index
    @patients = Patient.all
    # @patients = Patient.where(doctor_id: @doctor.id)
  end

  def show
    @patient = Patient.find(params[:id])
  end

  def new
    @patient = Patient.new(patient_params)
  end

  def create
    @patient = Patient.new(patient_params)
    if @patient.save
      redirect_to new_before_exercise_path
    else
      render :new
    end
  end

  private

  def patient_params
    params.require(:patient).permit(:first_name, :last_name, :age, :address, :gender, :phone_number, :previous_illness) 
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MoodTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
  <div class= "small-container mt-3">
    <div class = "right-container">
      <h1>Hi, welcome to moodTracker !!</h1>
      <p>Find me in app/views/pages/home.html.erb</p>
    </div>
    <div>
     <img class = "image" src="https://i.pinimg.com/564x/92/1f/38/921f38dcdcba6b0b7648aba2fff17f59.jpg" alt="someone happlily running illustration">
    </div>
  </div>
</div>

app/views/patient/index.erb
<div class="container">
  <div>
    <h1>Patients</h1>
    <% @patients.each do |patient|%>
    <h2><% patient.first_name %>, <% patient.last_name %></h2>
    <p> <% patient.age %></p>
  </div>
</div>

app/views/patients/index.html.erb
<div class="container">
  <div>
    <h1>Patients</h1>
    <% @patients.each do |patient|%>
    <h2><%= link_to "#{patient.first_name}, #{patient.last_name}", patients_path(patient) %></h2>
    <p> <% patient.age %></p>
    <% end %>
  </div>
</div>

app/views/patients/new.html.erb
<div class="container">
  <div>
      <%= simple_form_for @patient do |f| %>
      <%= f.input :first_name %>
      <%= f.input :last_name %>
      <%= f.input :age %>
      <%= f.input :previous_illnes %>
      <%= f.input :phone_number %>
      <%= f.input :address %>
      <%= f.input :doctor %>  
      <%= f.button :submit, class: 'btn btn-primary' %>
    <% end %>
  </div>
  <%= link_to "Go back", root_path, class: "btn btn-primary my-3" %>
</div>

app/views/patients/show.html.erb
<div class="container">
  <div>
    <h2><%= @patient.first_name %>, <%= @patient.last_name %></h2>
    <h3><%= @patient.age %></h3>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Profile", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Stadistics", "#", class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sing up", new_user_registration_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>